FROM rust:1.44

RUN rustup install nightly && \
    rustup default nightly

RUN cargo install diesel_cli --no-default-features --features mysql

COPY .bashrc /root/.bashrc
COPY .inputrc /root/.inputrc

WORKDIR /opt/holiday_bot/
RUN cp .env_example .env